### ISSUE TITLE
Remove xblockutils package

### ISSUE THREAD

**Issue by farhan** [openedx/edx-enterprise#1902]
Parent ticket: https://github.com/openedx/axim-engineering/issues/915

This repository is using the [xblock-utils](https://github.com/openedx/xblock-utils/) package which has been deprecated and migrated to within the xblock package.

In this ticket, we will:
```[tasklist]
### Tasks
- [x] Make sure the repository is using xblock [version 1.8.1](https://github.com/openedx/XBlock/releases/tag/xblock-1.8.0) or above. Upgrade the version if required, preferably via the `make upgrade` command.
- [x] Remove the `xblock-utils` package
- [x] Find and replace all the `xblockutils.*` imports with `xblock.utils.*`
- [x] Make sure all the test cases are passing
- [x] Test the xblock
```

**Comment by feanil** [comment]
This is only because edx-enterprise keeps a copy of the edx-platform base.txt as a constraints file.  So once edx-platform has removed that dependency, this should get removed automatically.  I saw no evidence of the xblock-utils code in use in this repo.
